### ISSUE TITLE
[DocumentDetector] Attempt to invoke virtual method on a null object reference

### ISSUE THREAD

**Issue by leonardosilva-asaas** [combateafraude/Flutter#27]
Olá,
Recebemos um crash no nosso Crashlytics relacionado à biblioteca DocumentDetector.
<details>
<summary>stacktrace</summary>

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.combateafraude.documentdetector.o.a.a()' on a null object reference
       at com.combateafraude.document_detector.DocumentDetectorPlugin.getSucessResponseMap(DocumentDetectorPlugin.java:341)
       at com.combateafraude.document_detector.DocumentDetectorPlugin.onActivityResult(DocumentDetectorPlugin.java:375)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:840)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:441)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:772)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:685)
       at br.com.codemoney.common.flutter.AMFlutterActivity.onActivityResult(AMFlutterActivity.kt:94)
       at android.app.Activity.dispatchActivityResult(Activity.java:8569)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5416)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5462)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2293)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:329)
       at android.app.ActivityThread.main(ActivityThread.java:8058)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```
</details>

Olhando o código fonte de vocês parece que `capture` está nulo na [linha 341 do `DocumentDetectorPlugin.java`](https://github.com/combateafraude/Flutter/blob/fb074c2f2b774641932f018d3e5cd36828ea1c52/android/src/main/java/com/combateafraude/document_detector/DocumentDetectorPlugin.java#L341).

O crash ocorreu em um dispositivo com Android 12. A versão que estamos utilizando do DocumentDetector é a disponível na tag `document-detector-nodatabinding-v6.1.0`.

Obrigado!

**Comment by murilofank** [comment]
This version has been discontinued, and we will no longer provide support for it.
