### ISSUE TITLE
[DocumentDetector] Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference

### ISSUE THREAD

**Issue by leonardosilva-asaas** [combateafraude/Flutter#29]
Olá,
Recebemos um crash no nosso Crashlytics relacionado à biblioteca DocumentDetector.

<details>
<summary>stacktrace</summary>

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
       at com.combateafraude.documentdetector.controller.DocumentDetectorController.b(DocumentDetectorController.java:20)
       at com.combateafraude.documentdetector.controller.DocumentDetectorController.lambda$vK_8WDJphNyLzoaUpyAMZ2sofRo(DocumentDetectorController.java)
       at com.combateafraude.documentdetector.controller.-$$Lambda$DocumentDetectorController$vK_8WDJphNyLzoaUpyAMZ2sofRo.run(lambda:8)
       at java.lang.Thread.run(Thread.java:919)
```
</details>

O crash ocorreu em um dispositivo Galaxy J6+ rodando Android 10. Utilizamos a lib na versão da tag `document-detector-nodatabinding-v6.1.0`.

**Comment by murilofank** [comment]
This version has been discontinued, and we will no longer provide support for it.
