### ISSUE TITLE
[DocumentDetector] java.lang.NullPointerException: Attempt to invoke interface method 'void androidx.camera.core.w2.close()' on a null object reference

### ISSUE THREAD

**Issue by jacsongsj-asaas** [combateafraude/Flutter#31]
Olá,
Recebemos um crash no Crashlytics relacionado à biblioteca DocumentDetector.

<details>

<summary>
Stacktrace
</summary>

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {br.com.codemoney.customer/com.combateafraude.documentdetector.DocumentDetectorActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { cmp=br.com.codemoney.customer/com.combateafraude.documentdetector.PreviewActivity (has extras) }} to activity {br.com.codemoney.customer/com.combateafraude.documentdetector.DocumentDetectorActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void androidx.camera.core.w2.close()' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4578)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4610)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2144)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:240)
       at android.app.ActivityThread.main(ActivityThread.java:8000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
</details>

O crash ocorreu em um dispositivo Moto G20 rodando Android 11. Utilizamos a lib na versão da tag document-detector-nodatabinding-v6.1.0.

**Comment by murilofank** [comment]
This version has been discontinued, and we will no longer provide support for it.
